title: Alan Bao
color: 2ad9fa
logo: /img/itsjoever.png
description: professional slots player
theme: jekyll-theme-minimal
github: False
#image:
  #background: /img/itsjoever.png

author:
  name: Alan Bao
  email: alanb@berkeley.edu

