title: Alan Bao
color: 2ad9fa
logo: /img/itsjoever.png
description: Personal Portfolio
theme: jekyll-theme-minimal
github: False
image:
  background: /img/chicken.png

author:
  name: Alan Bao
  email: alanb@berkeley.edu

