title: Alan Bao [![linkedin](img/linkedin.png)](http://linkedin.com/in/alan-bao/)  <a href="mailto:alanb@berkeley.edu">![email](img/email.png)</a>
logo: /img/itsjoever.png
description: professional slots player
theme: jekyll-theme-minimal

author:
  name: Alan Bao
  email: alanb@berkeley.edu
#photo: /assets/jpg/photo.jpg


# social media links

social:
  github: abao27
  linkedin: alan bao
