title: Alan Bao's Personal Website
color: 2ad9fa
logo: /img/prof_photo.jpeg
theme: jekyll-theme-minimal
github: False
description: UC Berkeley Class of 2026 

author:
  name: Alan Bao
  email: alanb@berkeley.edu

