title: Alan Bao
logo: /img/itsjoever.png
description: professional slots player
theme: jekyll-theme-minimal

author:
  name: Alan Bao
  email: alanb@berkeley.edu
#photo: /assets/jpg/photo.jpg


# social media links

social:
  github: abao27
  linkedin: alan bao
