title: Alan Bao's Personal Website
color: 2ad9fa
logo: /img/prof_photo_circle.png
theme: jekyll-theme-minimal
github: False
description: UC Berkeley '26 

author:
  name: Alan Bao
  email: alanb@berkeley.edu

