title: Alan Bao
color: 2ad9fa
description: Personal Portfolio
#logo: /img/chicken.png
theme: jekyll-theme-minimal
github: False
image: /img/chicken.png

author:
  name: Alan Bao
  email: alanb@berkeley.edu

