title: Alan Bao's Personal Website
color: 2ad9fa
logo: /img/chicken.png
theme: jekyll-theme-minimal
github: False
description: Surprised Chicken!!

author:
  name: Alan Bao
  email: alanb@berkeley.edu

