title: Alan Bao
logo: /img/itsjoever.png
description: professional slots player
theme: jekyll-theme-minimal

author:
  name: Alan Bao
  email: alanb@berkeley.edu
#photo: /assets/jpg/photo.jpg

# social media links

social:
  facebook: alanb
  github: abao27
  instagram: alan._.xb
  linkedin: alan bao
  stackoverflow: 0000000/username
  twitter: username
